spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fnst-3d3k
  redis:
    host: localhost
    port: 6379

# mybatis config
mybatis:
  type-aliases-package: com.example.shop.entity
  mapper-locations: classpath:db/mybatis/*.xml


#pagehelper plugin configuration
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
