spring:
  application:
    name: shop
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/shop?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fnst-3d3k
  redis:
    host: 192.168.1.12
    port: 6379


# mybatis config
mybatis:
  mapper-locations: classpath:db/mybatis/*.xml

#pagehelper plugin configuration
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

shop:
  service:
    version: 1.0.0
    url: ""
  redis:
    host: 192.168.1.12
    port: 6379

dubbo:
  registry:
    address: zookeeper://146.56.220.117:2181
    
server:
  port: 8080

