spring:
  application:
    name: shop-order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fnst-3d3k
  redis:
    host: 127.0.0.1
    port: 6379

dubbo:
  scan:
    base-packages: com.example.shop.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181

shop:
  service:
    version: 1.0.0
