CREATE TABLE user
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME   VARCHAR(100) UNIQUE
        COMMENT '用户名',
    TEl        VARCHAR(20) UNIQUE
        COMMENT '用户名',
    PASSWORD   VARCHAR(100) COMMENT '密码',
    AVATAR_URL VARCHAR(100) COMMENT '头像',
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
)
